export const START_FETCHING = 'START_FETCHING';
export const END_FETCHING = 'END_FETCHING';
export const ADD_ENTITY = 'ADD_ENTITY';
export const REMOVE_ENTITY = 'REMOVE_ENTITY';
export const CHECKING_AUTHENTICATION = 'CHECKING_AUTHENTICATION';
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';
export const AUTHENTICATION_REQUIRED = 'AUTHENTICATION_REQUIRED';
